### PR TITLE
Fixed typo and edited flag help

### PR DESCRIPTION
**Pull request by olliephillips**

### CODE REVIEW

**Comment by rekby** [comment]
Hello. Thanks for your help.

I think about update of --whitelist-domains will be better. And write about --whitelist-domains-file it same, but get domains from file.
In current version descriptions are difference and it understanding as different sense.

**Comment by olliephillips** [comment]
No problem, and yes, I see your point.  So I should move this text "When using this flag --non-cert-domains=\".*\" also needs to be set." into the `--whitelist-domains` flag help instead?

**Comment by rekby** [comment]
Yes. And I think about change "When using this flag --non-cert-domains=".*" also needs to be set" to "the parameter doesn't reject other domains. For reject domains use parameter --non-cert-domains. For reject all domains but white list use --non-cert-domains=".*".

**Comment by olliephillips** [comment]
No problem, I'll sort this. The * is not required for the regex? I've been using .* fine.

**Comment by olliephillips** [comment]
I don't want to delay you. Thanks for giving me the opportunity to contribute a bit back :)

**Comment by rekby** [comment]
Thanks for your help.

**Pull request merged**
